using UnityEngine;
using UnityEngine.SceneManagement;
using System.Collections;

public class PauseMenu : MonoBehaviour
{
    [SerializeField] GameObject pauseMenu;

    public void Pause()
    {
        pauseMenu.SetActive(true);
        Time.timeScale = 0;
    }

    public void Home()
    {
       
        SavePlayerPos playerPosData = FindObjectOfType<SavePlayerPos>();
        if (playerPosData != null)
        {
            playerPosData.PlayerPosSave();
        }

        SceneManager.LoadScene("MainMenu");
    }

    public void Resume()
    {
        pauseMenu.SetActive(false);
        Time.timeScale = 1;
    }

    private void OnEnable()
    {
        SceneManager.sceneLoaded += OnSceneLoaded;
    }

    private void OnDisable()
    {
        SceneManager.sceneLoaded -= OnSceneLoaded;
    }

    private void OnSceneLoaded(Scene scene, LoadSceneMode mode)
    {
        if (scene.name == "Game")
        {
            StartCoroutine(ResumeTimeScaleAfterFrame()); 
        }
    }

    private IEnumerator ResumeTimeScaleAfterFrame()
    {
        yield return null; 
        Time.timeScale = 1; 
    }
}
